raw_data: data/raw
proc_data: data/processed/
cache_file: data/processed/session_cache.json
out_fig: output/figures
out_logs: output/logs
gap_factor: 3 # should be > 1
motion_threshold_rad_s: 1
standstill_min_s: 3
wheel_radius: 0.19 # in m
pit_min_s: 60 # a pit stop is max of 3min but also could be longer than that or lesss than that, this is an assumtpion
grid_rate_hz: 250 # rationale is in 06_preprocess notebook
# cutoff per column prefix in Hz
#columns not listed are left unfiltered
# decided in notebooks/06_preprocess.ipynb
cutoffs: { 
    "pedal_brakes_pressure": 15, 
    "front_angular_velocity": 5,
    "imu_acceleration": 10,
    "imu_angular_rate": 10,
}

offset_channels: {
    "imu_angular_rate": ["x", "y", "z"],
    "imu_acceleration": ["x"],
}

files: [
    "hv_power",
    "imu_angular_rate",
    "imu_acceleration",
    "vehicle_position",
    "vehicle_speed",
    "vehicle_curvilinear_coordinates",
    "pedal_brakes_pressure",
    "pedal_throttle",
    "steer_angle",
    "front_angular_velocity",
    "inv_r_id_a8_n_actual_filt",
    "inv_l_id_a8_n_actual_filt",
    "inv_r_id_27_iq_actual",
    "inv_l_id_27_iq_actual",
]


