from src.utils import standstill_stats
from src.loader import load, load_centerline
from src.config import GRID_RATE_HZ, PROC_DATA, CUTOFFS
import pandas as pd
import numpy as np
from scipy.signal import butter, sosfiltfilt



OFFSET_CHANNELS = {
    "imu_angular_rate": ["x", "y", "z"],
    "imu_acceleration": ["x"],
}

FILES = [
    "hv_power",
    "imu_angular_rate",
    "imu_acceleration",
    "vehicle_position",
    "vehicle_speed",
    "vehicle_curvilinear_coordinates",
    "pedal_brakes_pressure",
    "pedal_throttle",
    "steer_angle",
    "front_angular_velocity",
    "inv_r_id_a8_n_actual_filt",
    "inv_l_id_a8_n_actual_filt",
    "inv_r_id_27_iq_actual",
    "inv_l_id_27_iq_actual",
]


def remove_offsets(channels=OFFSET_CHANNELS):
    """subtract standstill offsets. 
    
    returns dict {file: corrected DataFrame} and the offsets used
    
    """
    stats = standstill_stats(sensors=channels)
    stats = stats.pivot_table(index=["file", "column"], columns="window", values="mean")
    offsets = stats.mean(axis=1)

    corrected = {}
    for file, measure_values in channels.items():
        df = load(file).drop(columns=["imu_temperature"], errors="ignore")
        for col in measure_values:
            df[col] = df[col] - offsets.loc[(file, col)]
        corrected[file] = df

    return corrected, offsets



def unwrap(df: pd.DataFrame, col: str, period: float):
    
    """
    
    period is the full period of that column
    for exampe distance is 0 -> 805 so period = 805
    
    """
    
    data = df.copy()
    data[col] = np.unwrap(df[col], period=period)
    
    return data

def wrap(df: pd.DataFrame, col: str, period: float, low: float):
    data = df.copy()
    data[col] = ((data[col] - low) % period) + low
    
    return data
    

from src.profiler import find_gaps
 
def gap_intervals(dfs: dict) -> dict:
    
    """
    
    takes a dict of {file: DataFrame} and returns 
    a dict {file: DataFrame of intervals} of its gaps
    
    """
    
    return {file: find_gaps(df)[["start_s", "end_s"]] for file, df in dfs.items()}


def make_grid(dfs, rate):
    """
    build a common, evenly spaced time grid for all signals
    
    input:
        dfs: dict(str, dataframe)
        it's the signal per file each with a sorted 't_s' column
    rate in Hz
    
    output:
    grid times in seconds, spaced 1 / rate apart
    
    """
    
    start = max(df["t_s"].iloc[0] for df in dfs.values())
    end = min(df["t_s"].iloc[-1] for df in dfs.values())
    
    n = int((end - start) * rate) + 1
    grid = np.array(start + np.arange(n) / rate)
    
    return grid






def _runs(ok: np.ndarray):
    """
    (start, end) index pairs of consecutive True values
    end is exclusive
    
    """
    d = np.diff(np.concatenate(([0], ok.astype(int), [0])))
    return list(zip(np.flatnonzero(d == 1), np.flatnonzero(d == -1)))


def lowpass(df: pd.DataFrame, cutoffs: dict = CUTOFFS, fs: float = GRID_RATE_HZ, order: int = 4):
    """
    Zero-phase Butterworth low-pass filter, applied per NaN-free segment.

    each column whose name starts with a key of `cutoffs` is filtered at that cutoff.
    filtering runs forward and backward (sosfiltfilt) so events are
    not shifted in time, and separately on each continuous stretch between
    NaN gaps so gap edges don't leak into good data. 
    Segments too short for the filter are left unfiltered. 
    Other columns are returned unchanged.

    input:
    df : resampled signals on a regular grid at sampling rate 'fs'
    cutoffs : dict[str, float] column-name prefix -> cutoff frequency in Hz.
    fs : sampling rate of the grid in Hz
    order : Butterworth filter order.

    output
    a daatframe: copy of 'df' with the selected columns filtered.
    """
    out = df.copy()
    for prefix, fc in cutoffs.items():
        sos = butter(order, fc, btype="low", fs=fs, output="sos")
        min_len = 3 * (2 * len(sos) + 1)  # sosfiltfilt's default padding needs at least this many samples
        for col in [c for c in df.columns if c.startswith(prefix)]:
            x = df[col].to_numpy()
            y = x.copy()
            for a, b in _runs(~np.isnan(x)):
                if b - a > min_len:
                    y[a:b] = sosfiltfilt(sos, x[a:b])
            out[col] = y
    return out

def resample(dfs: dict, grid: np.ndarray, intervals: dict):
    """
    resample every signal onto a common time grid and mask gaps
    
    each signal is linearly interpolated from its own timestams on teh grid
    grid points strictly inside one of that file's gaps are set to NaN
    since interpolation there would invent data.
    
    each file is masked with its own gaps only
    
    input:
    dfs: dict(str, dataframe)
    it's the signal per file
    
    grid: evenly spaced time points generated by make_grid
    intervals: gaps per file from gap_intervals
    
    it returns a df with columns 't_s' and one column per signal named 'file__column'
    t_s here is the grid created (not the previous t_s we were working with)
    
    
    """
    
    # create a table
    interpolated = {"t_s": grid}

    for file, df in dfs.items():
        # identify each gap in that file with its start and end pairs
        gaps = intervals[file]
        lo = np.searchsorted(grid, gaps["start_s"].to_numpy(), side="right")
        hi = np.searchsorted(grid, gaps["end_s"].to_numpy(), side="left")

        for col in df:
            if col not in ("t_s", "_timestamp"):
                # compute interpolations (straight lines between the real values to estimate the value at grid time)
                values = np.interp(grid, df["t_s"], df[col])
                # the grid time that fall inside gaps of that file
                # remove them bc thats making guesses across missing data
                for a, b in zip(lo, hi):
                    values[a:b] = np.nan
                interpolated[f"{file}__{col}"] = values

    return pd.DataFrame(interpolated)



def run_preprocessing(files: list = FILES, rate: int = GRID_RATE_HZ, save: bool = True):
    """
    Run the preprocessing pipeline: load, remove IMU offsets, unwrap s and
    heading, find gaps, resample onto a common grid with gaps masked, and
    wrap s and heading back, and save to parquet.
    
    """
    
    
    # load files
    data = { file: load(file) for file in files}
    #replace imu files with offset corrected ones
    imu, offsets = remove_offsets()
    data.update(imu)
    
    # unwrap s and heading
    L = load_centerline().attrs["length"]
    data["vehicle_curvilinear_coordinates"] = unwrap(data["vehicle_curvilinear_coordinates"], "s", L)
    data["vehicle_position"] = unwrap(data["vehicle_position"], "heading", 2 * np.pi)
    
    # find gap intervals
    gaps = gap_intervals(data)
    
    # build the grid
    grid = make_grid(data, rate)
    
    # resample +  mask gaps
    resampled = resample(data, grid, gaps)
    
    # wrap s and heading back
    resampled = wrap(resampled,"vehicle_curvilinear_coordinates__s", L, 0)
    resampled= wrap(resampled, "vehicle_position__heading", 2*np.pi, -np.pi)
    
    
    # low-pass filter
    resampled = lowpass(resampled, fs=rate)

    # save
    if save:
        PROC_DATA.mkdir(parents=True, exist_ok=True)
        resampled.to_parquet(PROC_DATA / "session.parquet", index=False)
        
    
    return resampled,  offsets
    

    
                
