from src.utils import standstill_stats
from src.loader import load


OFFSET_CHANNELS = {
    "imu_angular_rate": ["x", "y", "z"],
    "imu_acceleration": ["x"],
}


def remove_offsets(channels=OFFSET_CHANNELS):
    """subtract standstill offsets. 
    
    returns dict {file: corrected DataFrame} and the offsets used
    
    """
    stats = standstill_stats(sensors=channels)
    stats = stats.pivot_table(index=["file", "column"], columns="window", values="mean")
    offsets = stats.mean(axis=1)

    corrected = {}
    for file, measure_values in channels.items():
        df = load(file).drop(columns=["imu_temperature"], errors="ignore")
        for col in measure_values:
            df[col] = df[col] - offsets.loc[(file, col)]
        corrected[file] = df

    return corrected, offsets

import pandas as pd
import numpy as np

def unwrap(df: pd.DataFrame, col: str, period: float):
    data = df.copy()
    data[col] = np.unwrap(df[col], period=period)
    
    return data

def wrap(df: pd.DataFrame, col: str, period: float, low: float):
    data = df.copy()
    data[col] = ((data[col] - low) % period) + low
    
    return data
    

from src.profiler import find_gaps
 
def gap_intervals(dfs: dict) -> dict:
    
    """
    
    takes a dict of {file: DataFrame} and returns 
    a dict {file: DataFrame of intervals} of its gaps
    
    """
    
    return {file: find_gaps(df)[["start_s", "end_s"]] for file, df in dfs.items()}


def make_grid(dfs, rate):
    """
    build a common, evenly spaced time grid for all signals
    
    input:
        dfs: dict(str, dataframe)
        it's the raw signal per file each with a sorted 't_s' column
    rate in Hz
    
    output:
    grid times in seconds, spaced 1 / rate apart
    
    """
    
    start = max(df["t_s"].iloc[0] for df in dfs.values())
    end = min(df["t_s"].iloc[-1] for df in dfs.values())
    
    n = int((end - start) * rate) + 1
    grid = np.array(start + np.arange(n) / rate)
    
    return grid

def resample(dfs: dict, grid: np.ndarray, intervals: dict):
    """
    resample every signal onto a common time grid and mask gaps
    
    each signal is linearly interpolated from its own timestams on teh grid
    grid points strictly inside one of that file's gaps are set to NaN
    since interpolation there would invent data.
    
    each file is masked with its own gaps only
    
    input:
    dfs: dict(str, dataframe)
    it's the raw signal per file each with a sorted 't_s' column
    
    grid: evenly spaced time points generated by make_grid
    intervals: gaps per file from gap_intervals
    
    it returns a df with columns 't_s' and one column per signal named 'file__column'
    t_s here is the grid created (not the previous t_s we were working with)
    
    
    """
    
    # create a table
    interpolated = {"t_s": grid}

    for file, df in dfs.items():
        # identify each gap in that file with its start and end pairs
        gaps = intervals[file]
        lo = np.searchsorted(grid, gaps["start_s"].to_numpy(), side="right")
        hi = np.searchsorted(grid, gaps["end_s"].to_numpy(), side="left")

        for col in df:
            if col not in ("t_s", "_timestamp"):
                # compute interpolations (straight lines between the real values to estimate the value at grid time)
                values = np.interp(grid, df["t_s"], df[col])
                # the grid time that fall inside gaps of that file
                # remove them bc thats making guesses across missing data
                for a, b in zip(lo, hi):
                    values[a:b] = np.nan
                interpolated[f"{file}__{col}"] = values

    return pd.DataFrame(interpolated)
                
